keys:
  - &stefan_ellmauthaler 3B398B086C410264A14FB353B1E6F03030A4AEAA
  - &stel-xps e8dfcfbac0c3e65bbdfd62ab534ab685d882e4ca
creation_rules:
  - path_regex: secrets/secrets\.yaml
    key_groups:
      - pgp:
          - *stefan_ellmauthaler
          - *stel-xps
